# Site settings
title: Jekyll-Uno(C9)
description: '- A minimal, responsive theme for Jekyll, useable with the Cloud9 IDE'
#url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/jekyll_uno_on_c9/'

# Google Analytics Tracking ID
google_analytics: 'UA-92171668-2'

# disqus_shortname: 'your-disqus-name'

# Modifications for Cloud9 Development.
port: 8080
host: 0.0.0.0

author:
  name: 'Benjamin Haos'
  email: benjaminhaos@gmail.com
  twitter_username: EntropyHaos
  #facebook_username: 
  github_username:  EntropyHaos
  linkedin_username:  benjaminhaos

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
# Limit the number of posts shown on each page:
paginate: 4
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
